export const SELECT_PRODUCT = "SELECT_PRODUCT";
export const SELECT_PRODUCT_ERR = "SELECT_PRODUCT_ERR";
export const SELECT_POST = "SELECT_POST";
export const SELECT_POST_ERR = "SELECT_POST_ERR";

export const SELECT_CMT_ERR ="SELECT_CMT_ERR";
export const SELECT_CMT ="SELECT_CMT";

